### ISSUE TITLE
How to calculate the last result scores in the table?

### ISSUE THREAD

**Issue by zerlinwang** [nikhilbarhate99/min-decision-transformer#1]
As shown in the table, DT (this repo) got 69.43 in Hopper and 75.47 in Walker2d. I would like to ask how these scores calculated from the csv results?

**Comment by nikhilbarhate99** [comment]
The final scores are not calculated from the csv file. The csv files are just logging training and evaluation data.

I am not sure what the authors mean in the Decision Transformer paper when they state that "_We report the mean and variance for three seeds_."

The `DT (this repo)` mean and variance scores are calculated after 3 training runs with different random seeds have ended (20k updates). Then loading those 3 saved models and averaging their evaluation performance in the environment for 10 episodes for each saved model.
