### ISSUE TITLE
The calculation of state_mean and state_std in d4rl_info.py

### ISSUE THREAD

**Issue by justcrossheaven** [nikhilbarhate99/min-decision-transformer#3]
Hello there, we are currently trying to use the code to give some other dataset a go, like walker2d-random-v2. So we would like to kindly ask how state_mean and state_std in d4rl_info are calculated, or whether there is any open data for these values. Thank you very much!

**Comment by nikhilbarhate99** [comment]
They are calculated from the dataset.
Refer to 1st block of 'dataset' section in the ipynb file.

you can remove the last 4 print and assert statements, instead add the calculated stats to `D4RL_DATASET_STATS` dictionary.

**Comment by justcrossheaven** [comment]
> They are calculated from the dataset. Refer to 1st block of 'dataset' section in the ipynb file.
> 
> you can remove the last 4 print and assert statements, instead add the calculated stats to `D4RL_DATASET_STATS` dictionary.

Thanks for ur reply, that helps a lot :)
